# Generated by Django 4.2 on 2024-01-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/blog')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
